Upstream debian patches and a minor fix of mine
PADL/pam_ccreds pull request #1
Opened 2018-06-01 11:36 UTC by g0hl1n

This PR aims to upstream the patches from Debians libpam-ccreds (https://packages.debian.org/stretch/libpam-ccreds) source archive.
Furthermore I've added a minor fix for the EXTENSION_SO conditional.

2018-06-04 07:55 UTC, g0hl1n commented
Improved EXTENSION_SO patch to match all linux* targets.

2018-07-17 13:53 UTC, g0hl1n commented
@PADL / @lhoward  any updates/comments on this PR?

2018-07-20 06:20 UTC, lhoward requested changes
Just a couple of things – uid_t and also getpwnam_r()

2018-07-20 06:20 UTC, lhoward commented on cc_pam.c
> +		pwd = getpwnam(username);
Might be safer to use getpwnam_r() so we don't disturb any state in the calling application.

2018-07-20 06:20 UTC, lhoward commented on cc_pam.c
> +	int minimum_uid = 0;
uid_t might be better?

2018-07-20 06:20 UTC, lhoward commented on cc_pam.c
> +_pamcc_should_ignore(const char *username, int minimum_uid)
uid_t minimum_uid

2018-08-01 14:10 UTC, g0hl1n commented
I've just updated the PR. Hope it's fine now

2018-08-02 03:52 UTC, lhoward approved these changes

2018-08-02 03:52 UTC, merged